packaging: add BuildRequires for capnproto and cargo
The specfile must advertise cargo and capnproto as build requirements so that
builds by koji (used by redhat and by toss) can install those packages on build
hosts before beginning the build via rpmbuild.

This is independent of the dependency system provided by cargo.

Fixes
	+ CARGO_PROFILE_RELEASE_DEBUG=true
	+ cargo build --release
	/var/tmp/rpm-tmp.IwExIa: line 46: cargo: command not found
	error: Bad exit status from /var/tmp/rpm-tmp.IwExIa (%build)
	RPM build warnings:
	RPM build errors:
	    source_date_epoch_from_changelog set but %changelog is missing
	    Bad exit status from /var/tmp/rpm-tmp.IwExIa (%build)
	Child return code was: 1

and
	   Compiling halo v0.1.1 (/builddir/build/BUILD/halo-0.1.1)
	error: failed to run custom build command for `halo v0.1.1 (/builddir/build/BUILD/halo-0.1.1)`
	Caused by:
	  process didn't exit successfully: `/builddir/build/BUILD/halo-0.1.1/target/release/build/halo-7a888c6b24cb7ef7/build-script-build` (exit status: 1)
	  --- stdout
	  cargo::rerun-if-changed=halo.capnp
	  --- stderr
	  Error: Error { kind: Failed, extra: "Failed to execute `capnp --version`: No such file or directory (os error 2). Please verify that version 0.5.2 or higher of the capnp executable is installed on your system. See https://capnproto.org/install.html" }